datasources:
  postgres:
    url: jdbc:postgresql://host.docker.internal:5432/kestra
    driver-class-name: org.postgresql.Driver
    username: kestra
    password: kestra
kestra:
  server:
    port: 8080
  repository:
    type: postgres
  queue:
    type: postgres
  storage:
    type: local
    local:
      base-path: "/app/storage"

# Cette section corrige l'erreur "No bean of type MeterRegistry"
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: false # On l'active mais on n'exporte rien pour l'instant

management:
  endpoints:
    all:
      enabled: true